### ISSUE TITLE
Local storage for .GPX files 

### ISSUE THREAD

**Issue by robertaustinbell** [flathub/org.openstreetmap.josm#1]
Its awesome to have JOSM on Flathub! Thank you for getting it up!
Is there a way to be able to use .GPX files that are needed for things like the HOT tasking manager?
It doesn't look like i has permissions for storage and I cant launch it via remote control.

**Comment by muelli** [comment]
Currently the app does not have any dedicated permission for the filesystem. What it does have is its custom app directory `~/.var/app/org.openstreetmap.josm/`.

It's easy to relax the sandbox and allow to read and write to a certain path. Is that what you envision? Which path are you thinking of?

**Comment by robertaustinbell** [comment]
If I could copy and paste files into ~/.var/app/org.openstreetmap.josm/ that would be OK but its locked down. The most convenient path would be the downloads folder. So you could download something to the default folder and open it without having to move it around. 
Alternatively if the Remote Control feature worked that would allow me to launch things directly form the HOT tasking manager without downloading anything. :-)  it already has networking working so would it just be opening up a port?
https://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl
https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl
The Flatpak sandbox should provide isolation so I would not mind leaving the port open.

**Comment by muelli** [comment]
> If I could copy and paste files into ~/.var/app/org.openstreetmap.josm/ that would be OK but its locked down.

umm. that sounds weird. I can create a file from the host and see it from within the app:

![image](https://user-images.githubusercontent.com/322807/48676111-4dd61c00-eb62-11e8-84aa-039819f173c6.png)


![image](https://user-images.githubusercontent.com/322807/48676108-3dbe3c80-eb62-11e8-8352-787c44cf53aa.png)

Does that not work for you? That'd be strange, at best.

**Comment by robertaustinbell** [comment]
That doesn't work for me. Also my file structure looks a little different. (This might be lack of experience on my part or the fact that im running Clear Linux) but it looks like my app is located at 
/var/lib/flatpak/repo/refs/remotes/org.openstreetmap.josm-origin/app/org.openstreetmap.josm/x86_64
I was able to move a file into there after I remembered to sudo since root owns the folder. However I was still not able to see the file in JOSM. 
https://clearlinux.org

**Comment by muelli** [comment]
nah. `~/.var/app/org.openstreetmap.josm/` is in your home directory and flatpak will set it up correctly. If that doesn't work, then it's a serious bug in Flatpak. It's not bug free, but I doubt that it'd go unnoticed for long.  Does this directory not exist?

Can you try to `touch ~/.var/app/org.openstreetmap.josm/data/foo.gpx` and then navigate with JOSM there, i.e. type `.var` once the file picker pops up and presents you an empty home directory.

**Comment by robertaustinbell** [comment]
Yes that did work thank you.

**Comment by muelli** [comment]
so is this a non-issue? I don't understand your use-case with that HOT task manager nor what it is.

**Comment by robertaustinbell** [comment]
I was able CD into the directory, move the file from my downloads folder and see it once I typed in .var in the search box then the file appeared. (I don't know why that worked).
Here is a project im working on with the HOT manager now 
https://tasks.openstreetmap.us/project/76?task=108
The work flow involves picking a area to work locking it and using JOSM to do the work then marking it complete. normally you enable the remote control feature of JOSM and once you lock the task on the manager it automatically pulls down the area you selected in JOSM for you to work on. But you can also download the .gpx to do the same thing manually to define the area you are working on from the manager to JOSM.

**Comment by muelli** [comment]
so... can we close this then or is there anything left to be done?

**Comment by robertaustinbell** [comment]
Yes, it can be closed. Thanks again for the help!
