### ISSUE TITLE
JOSM crashes consistently after around 2 minutes of usage on Fedora 36 KDE

### ISSUE THREAD

**Issue by ticotaco72** [flathub/org.openstreetmap.josm#76]
Will provide logs and other info if given instructions.

**Comment by muelli** [comment]
for starters, you could run the app from the command line, e.g. flatpak run org.openstreetmap.josm, and paste what it prints.

**Comment by ticotaco72** [comment]
Sorry for not writing it here, adding permission for running in background resolved the problem
